### ISSUE TITLE
Add a "road to full spec" roadmap to Wiki

### ISSUE THREAD

**Issue by MartijnHols** [WoWAnalyzer/WoWAnalyzer#1292]
We will soon have at least a basic version for all specs, so we should remove the "add a spec" docs to reduce the bloat. Still half of its info is also relevant for existing specs so we should try to give that a new home.

I suggest making a roadmap for creating a full spec that is sort of like a numbered checklist. This should make it easier to jump into a spec that is half done. It would be something like:

- [x] 1. Setup spec skeleton
       Go over config/changelog/healing/damage done/damage taken statistics.
- [ ] 2. Add the entire spellbook to the Abilities module
  - [ ] 2.1. isOnGCD
  - [ ] 2.2. Setup cast efficiency.
- [ ] 3. Add an analyzer
- [ ] 4. Add the checklist
