### ISSUE TITLE
[Marksmanship] Review all current suggestions and modules

### ISSUE THREAD

**Issue by Pewtro** [WoWAnalyzer/WoWAnalyzer#1617]
With the large amount of changes coming to hunter in BFA, all our current suggestions and modules need to be updated to be accurate come BFA. 

As of 23/4/2018 everything is still fluctuating a lot, but addons were recently allowed, so hopefully big class changes will be cooling down.

**Comment by Pewtro** [comment]
### To-do: 

- [ ] Lone-Wolf needs a whitelist to only allow following spells: https://raw.githubusercontent.com/Pewtro/wowdev/master/LoneWolfWhitelist
- [ ] Hunter's mark bug needs fixing
- [ ] Update all legendaries to be accurate 
        - Zevrims, Unseen Predator's Cloak, Celerity of the Windrunners off the top of my head
- [ ] more as I remember

**Comment by Pewtro** [comment]
Opening separate issues for everything.
