### ISSUE TITLE
Update "Be well prepared" checklist item for BFA

### ISSUE THREAD

**Issue by Gebuz** [WoWAnalyzer/WoWAnalyzer#1982]
- [x] Remove the legendary and legendary upgrade check
- [x] Update list of best enchants
- [x] Update list of potions
- [x] Add check for flask
- [x] Add check for best flask (same as enchants)
- [x] Add check for foodbuff
- [x] Add check for best foodbuff (same as enchants)
- [ ] Add check for gems (X/Y gem slots not empty)
- [ ] Add check for best gems (same as enchants)

**Comment by 5chmidt** [comment]
Hey, I am starting work on my first PR for wowanalyzer and I found this open item.

I checked a [recent report](https://wowanalyzer.com/report/HzZnMgTJA7mxFP6h/7-Heroic+Mythrax+-+Kill+(6:55)/1-Holyschmidt)  of mine which shows me as falsely unprepared.  The warcraftlogs shows I am [flasked](https://www.warcraftlogs.com/reports/HzZnMgTJA7mxFP6h/#fight=7&source=1&type=auras&ability=251837) and [well fed](https://www.warcraftlogs.com/reports/HzZnMgTJA7mxFP6h/#fight=7&source=1&type=auras&ability=259455).  The flask/ well fed is incorrectly reporting on both the my current branch and production build.

Could someone please point in the right direction to start working on this item.
Thanks,

**Comment by Pewtro** [comment]
Hey @5chmidt ! 

Awesome that you want to work on the project. Your issue seems to be a one-off issue, where the buffs were logged as being applied in combat (in fact up to over 2 seconds into combat). This makes the current code be working accurately and as intended. 

![image](https://user-images.githubusercontent.com/29204244/49562893-c76d5880-f91d-11e8-9b64-48a6c82e214c.png)
