### ISSUE TITLE
[General] Azerite Trait Checklist

### ISSUE THREAD

**Issue by TJMoats** [WoWAnalyzer/WoWAnalyzer#2242]
The purpose of this issue is to track which non-class specific Azerite traits have been added to WoWAnalyzer.

# General:

- [ ] Earthlink
- [ ] Blood Siphon
- [ ] Lifespeed
- [ ] On My Way
- [ ] Unstable Flames
- [x] Heed My Call

# Tank:

- [ ] Ablative Shielding
- [x] Crystalline Carapace
- [ ] Winds of War
- [ ] Azerite Veins
- [ ] Strength in Numbers
- [ ] Shimmering Haven

# Healer:

- [x] Synergistic Growth
- [x] Ephemeral Recovery
- [x] Blessed Portents
- [x] Bracing Chill
- [x] Concentrated Mending
- [x] Savior
- [x] Woundbinder

# Non-Healer:

- [ ] Azerite Globules
- [x] Gutripper
- [x] Elemental Whirl
- [x] Overwhelming Power

# Defensive:

- [x] Gemhide
- [ ] Impassive Visage
- [ ] Vampiric Speed
- [ ] Longstrider
- [ ] Resounding Protection
- [ ] Self Reliance
- [ ] Azerite Fortification
- [ ] Bulwark of the Masses

# Location:

## Nazmir
- [x] Blood Rite 
- [ ] Filthy Transfusion

## Zuldazar
- [ ] Incite the Pack
- [ ] Rezan's Fury

## Drustvar
- [x] Blightborne Infusion
- [ ] Ruinous Bolt

## Vol'dun
- [x] Swirling Sands
- [ ] Thunderous Blast

## Stormsong Valley
- [x] Tidal Surge 
- [ ] Secrets of the Deep

## Tiragarde Sound
- [x] Meticulous Scheming 
- [ ] Dagger in the Back 
- [x] Tradewinds

## The MOTHERODE!!
- [x] Unstable Catalyst

## Champions of Azeroth
- [ ] Champion of Azeroth

# Engineering: 
- [ ] Barrage Of Many Bombs
- [ ] Ricocheting Inflatable Pyrosaw
- [ ] Relational Normalization Gizmo
- [ ] Synaptic Spark Capacitor
- [ ] Auto-Self-Cauterizer
- [ ] Personal Absorb-o-Tron

# PVP

## Alliance
- [ ] Anduin's Dedication
- [ ] Battlefield Precision
- [ ] Stand As One
- [ ] Liberator's Might
- [ ] Last Gift
- [ ] Stronger Together

## Horde
- [ ] Sylvanas' Resolve
- [ ] Battlefield Focus
- [ ] Collective Will
- [ ] Glory in Battle
- [ ] Retaliatory Fury
- [ ] Combined Might

**Comment by Dambroda** [comment]
Pull request #2258 resolves Non-healer: Gutripper

**Comment by joshinat0r** [comment]
Updated the list

**Comment by joshinat0r** [comment]
Updated the list

**Comment by joshinat0r** [comment]
Updated it
