### ISSUE TITLE
[HPriest] Todo List

### ISSUE THREAD

**Issue by TJMoats** [WoWAnalyzer/WoWAnalyzer#2575]
This is a short list of improvements that can be made to the holy priest analyzer.

- [x] Implement a renew warning. Renew should be used no more than 5 times per minute as it is one of the lease efficient healing spells holy priests have. It would be nice to be able to say "only cast this when moving" but logs may not have enough information to do this.

- [ ] Implement a filler spell module similar to the Holy Paladin filler card: 
![screen shot 2018-11-02 at 7 39 53 am](https://user-images.githubusercontent.com/716498/47921723-8b545d00-de72-11e8-8630-6a10eb71cdc2.png)

- [ ] Add mastery values to the Mana Efficiency tracker tab

**Comment by Gebuz** [comment]
You can see if the player was stood still when casting Renew, I used it for bad dot refreshes here:
https://github.com/WoWAnalyzer/WoWAnalyzer/blob/bd9861d155d1e72da54bfd3714e997a7b8177f84/src/parser/shared/modules/earlydotrefreshes/EarlyDotRefreshesInstants.js#L74

**Comment by TJMoats** [comment]
Thanks, I didn't realize that was a thing. I've opened #2593 adding that.

**Comment by TJMoats** [comment]
Out of Date
