### ISSUE TITLE
[SPriest] Todo List

### ISSUE THREAD

**Issue by TJMoats** [WoWAnalyzer/WoWAnalyzer#2576]
- [ ] Fortress of the Mind talent card
- [ ] Shadowy Insight talent card
- [ ] Shadow Word Void talent card
- [ ] Misery talent card
- [ ] Dark Void talent card [Notes from Djriff: See how many adds you got with DV]
- [ ] Shadow Word Death talent card
- [ ] Lingering Insanity talent card
- [ ] Mind Bender talent card
- [ ] Dark Ascension talent card [Notes from Djriff: Should be used on cooldown essentially. Assuming good VF's first VF should be ~25s, 2nd around 20. That leaves ~5s of downtime between VF's. Can either add a check to see if it's used in VF, or just used on CD. Not entirely sure which is better. Adds, Track how well DA is utilized when the cooldown lines up with adds (give or take 5s on add spawn times from CD being up) Cooldown tracking added, I don't know how to show effective dps from this]
- [ ] Surrender to Madness talent card
- [ ] Implement an insanity tracking module. This doesn't need a card, but it should track insanity gains/spending across a fight. It should track how much insanity is wasted before entering shadow-form and do it's best to calculate overall insanity per spell. it would be nice if you could query it at a timestamp and get current insanity.
- [ ] #2612 Azerite Traits

**Comment by Pewtro** [comment]
As #3695 exists I am closing this. 

@Sharrq Maybe you can steal some things from here if you need more to add to #3695
