### ISSUE TITLE
[Restoration Shaman] 8.1 Checklist

### ISSUE THREAD

**Issue by niseko** [WoWAnalyzer/WoWAnalyzer#2631]
- [x] Add the 3 new Azerite traits mentioned in #2009
- [x] Remove Ebb and Flow, module and spreadsheet entry (Or keep it around for legacy support?)
- [x] Change Chain Heal to the new coefficient
- [x] Rework High Tide module to support the new talent
- [x] Add Buff usage and wasted buffs to the High Tide module (optional: detailed breakdown of each cast)
- [x] Remove High Tide changing Chain Heal to 5 targets from the ChainHeal module
- [x] Add High Tide buff to the Chain Heal spell timeline
- [x] Update the HealingRainLocation module with the new Overflowing Shores size (12 yards, non stacking)
- [x] Update traits.json as a lot of coefficients got changed (and entire azerite traits)
- [x] Update the UnleashLife module to a 35% heal increase
- (Optional) Split Chain Heal and High Tide into 2 spells for the Mana Efficiency module and other places where that distinction would make sense
- Might need to do something about "mana spent during innervate" for high tide as it extends your mana pool

**Comment by torothin** [comment]
Working on Check 5 - "Add Buff usage and wasted buffs to the High Tide module (optional: detailed breakdown of each cast)"

Submitted PR #3522

**Comment by torothin** [comment]
I think this issue can be closed out since PR#3522 was merged.
