### ISSUE TITLE
[Warlock] Implement Azerite traits

### ISSUE THREAD

**Issue by sMteX** [WoWAnalyzer/WoWAnalyzer#2724]
- [x] Affliction:
    - [x] ~~[Inevitable Demise](https://www.wowhead.com/spell=273521/inevitable-demise) (is changed in 8.1) - #2738~~ 
    - [x] ~~[Sudden Onset](https://www.wowhead.com/spell=278721/sudden-onset) - #2747~~ 
    - [x] ~~[Wracking Brilliance](https://www.wowhead.com/spell=272891/wracking-brilliance) - #2739~~
    - [x] ~~[Cascading Calamity](https://www.wowhead.com/spell=275372/cascading-calamity) - #2740~~
    - [x] ~~[Dreadful Calling](https://www.wowhead.com/spell=278727/dreadful-calling) (damage tuned in 8.1) - #2744~~
    - [ ] ~~[Deathbloom](https://www.wowhead.com/spell=275974/deathbloom) (lol, also is removed in 8.1)~~
- [x] Demonology:
    - [x] ~~[Demonic Meteor](https://www.wowhead.com/spell=278737/demonic-meteor) - #2749~~ 
    - [x] ~~[Supreme Commander](https://www.wowhead.com/spell=279878/supreme-commander) - #2750~~ 
    - [x] ~~[Explosive Potential](https://www.wowhead.com/spell=275395/explosive-potential) - #2751~~ 
    - [x] ~~[Shadow's Bite](https://www.wowhead.com/spell=272944/shadows-bite) - #2754~~ 
    - [x] ~~[Umbral Blaze](https://www.wowhead.com/spell=273523/umbral-blaze) - #2752~~ 
    - [x] ~~[Forbidden Knowledge](https://www.wowhead.com/spell=278738/forbidden-knowledge) (is removed in 8.1) - #2754~~ 
- [x] Destruction:
    - [x] ~~[Accelerant](https://www.wowhead.com/spell=272955/accelerant) (is removed in 8.1) - #2758~~ 
    - [x] ~~[Bursting Flare](https://www.wowhead.com/spell=279909/bursting-flare) - #2760~~ 
    - [x] ~~[Chaotic Inferno](https://www.wowhead.com/spell=278748/chaotic-inferno) - #2765~~ 
    - [x] ~~[Crashing Chaos](https://www.wowhead.com/spell=277644/crashing-chaos) - #2765~~ 
    - [x] ~~[Flashpoint](https://www.wowhead.com/spell=275425/flashpoint) - #2759~~ 
    - [x] ~~[Rolling Havoc](https://www.wowhead.com/spell=278747/rolling-havoc) - #2761~~ 
- [x] Shared:
    - [ ] ~~[Desperate Power](https://www.wowhead.com/spell=280022/desperate-power)~~
    - [ ] ~~[Lifeblood](https://www.wowhead.com/spell=274418/lifeblood)~~
- [x] 8.1:
    - [x] ~~[Pandemic Invocation](https://ptr.wowhead.com/spell=289364/pandemic-invocation) (replaces Deathbloom) - #2857~~ 
    - [x] ~~[Baleful Invocation](https://ptr.wowhead.com/spell=287059/baleful-invocation) (replaces Forbidden Knowledge) - #2855~~ 
    - [x] ~~[Chaos Shards](https://ptr.wowhead.com/spell=287637/chaos-shards) (replaces Accelerant) - #2856~~ 
    - [ ] ~~[Terror of the Mind](https://ptr.wowhead.com/spell=287822/terror-of-the-mind)~~
