### ISSUE TITLE
Update Feral Druid for 8.1

### ISSUE THREAD

**Issue by Anatta336** [WoWAnalyzer/WoWAnalyzer#2843]
Feral Druid had a bit of a rework in the 8.1 patch so needs some updates. I'm mainly making this as a todo list for myself, but of course anyone interested is welcome to contribute too!

- [x] Wild Charge (all versions) no longer triggers GCD. #2844 
- [x] Brutal Slash is now the best talent on the row for single target, so don't complain when the player uses it in single target. #2845 
- [x] Ferocious Bite no longer refreshes Rip against low health enemies by default. Update snapshot tracking code and remove suggestion to use Bite instead of Rip at low health. #2850
- [x] Sabertooth now causes Rip's duration to be extended up to a limit rather than reset. Update snapshot tracking to correctly mimic that. #2850
- [x] Rip's mechanics changed so number of combo points determines duration rather than strength. Update snapshot tracking for that. #2850
- [x] Refreshing the Rip early with low combo points can reduce the DoT's duration and lose the player damage. Detect that and generate a suggestion. #2850
- [x] The recommended opener for one of the most popular builds uses a low combo point finisher and the change to Rip makes using it at not-full combo points less of a damage loss than in 8.0. Loosen the "don't use finishers below 5 combo points" rule. #3188
- [x] Would be nice: Rather than just loosening the rule, make it smarter. Low combo point use of Rip on a target which doesn't have a Rip debuff yet should be allowed. Low combo point Ferocious Bite on a target with plenty of time left on its Rip should be flagged as a problem. #3188
- [x] Review the general advice in the "about feral druid" section for relevance to 8.1 #3021
- [x] Swap the example log for one from 8.1. #3021
- [x] New Azerite trait: Untamed Ferocity. Add analysis of damage increase and effective cooldown reduction. #2988 
- [x] Update Azerite trait: Wild Fleshrending. As Untamed Ferocity also increases damage of Shred and Swipe that needs to be taken into account to accurately calculate Wild Fleshrending's contribution if the player uses both. #2988 
- [x] New Azerite trait: Jungle Fury. Add analysis of uptime (should be simple as it is a separate buff.) #3018 
- [x] Azerite trait: Gushing Lacerations. Add analysis of damage increase and combo point generation. #3045 
- [x] Azerite trait: Iron Jaws. Add analysis of damage increase and suggestions if the buff isn't being properly used. #3022
- [ ] Basic analysis of Primal Wrath talent. If the fight was only single target suggest using Brutal Slash instead.
- [ ] Would be nice: Advanced analysis of Primal Wrath talent. The combat log doesn't differentiate between Rip applied by the talent and Rip applied by the single target ability. May get complex as the Rip can be extended by other abilities which makes attributing what ability the damage "belongs to" not simple.
- [ ] Analysis of the new Scent of Blood talent. Find how much energy is it saving the player, if that's very low (what threshold to use?) suggest using another talent. If fight was only single target suggest using Brutal Slash instead.
- [x] Jagged Wounds talent is removed, so remove any reference to it. #2850
- [x] With Rip's new mechanics the logic for using it to detect enemy death for the Predator talent will need reworking. (Removed incorrect version in #2850, still needs a replacement to be made)
- [x] Review the energy waste thresholds. A lot of highly ranked players are producing logs which trigger suggestions about energy waste.
- [ ] Would be nice: Rather than just loosening waste thresholds look at when wasting energy should be allowed. Berserk with high haste usually creates waste, especially in the standard opener. Waste during downtime periods is also unavoidable (outside of silly activity like spamming abilities which hit nothing.)
- [ ] Would be nice: Analysis of when it's worth upgrading the snapshot of Rip vs extending it with a Sabertooth'd Bite. Ideally you'd extend a fully upgraded Rip, but it may be a damage loss to spend resources upgrading it instead of getting the direct damage of Ferocious Bite. Fairly complex as need to predict the damage value of two different actions. Also not really a new 8.1 mechanic, just the popular build makes it a more relevant question.
- [x] Update Savage Roar analysis. Now increases damage by 10% instead of 15%, and increases energy regeneration by 10% while active. Will need to account for that in the energy cap tracking logic.
- [ ] Would be nice: Find out how much energy can be attributed to Savage Roar and report that.
- [ ] Aesthetics: Do a pass over all the Feral statistics, update to use the new `statistic` system and give as much visual uniformity as possible.

**Comment by Pewtro** [comment]
Closing as 8.1 is long gone, and Shadowlands awaits.
