### ISSUE TITLE
"Be Well Prepared" checklist for Shadowlands

### ISSUE THREAD

**Issue by Pewtro** [WoWAnalyzer/WoWAnalyzer#3664]
## Existing Features
- [x] Update list of best enchants
- [x] Update list of potions
- [x] Add check for flask
- [x] Add check for best flask (same as enchants)
- [x] Add check for foodbuff
- [x] Add check for best foodbuff (same as enchants)
## New Features
- [ ] Add check for gems (X/Y gem slots not empty)
- [ ] Add check for best gems (same as enchants)
- [x] Sharpening Stones https://shadowlands.wowhead.com/spells/professions/blacksmithing/shadowlands-plans/weapons-mods
- [x] Weight Stones https://shadowlands.wowhead.com/spells/professions/blacksmithing/shadowlands-plans/weapons-mods
- [x] Weapon Oils
- [ ] Legendary equipped check

**Comment by Sharrq** [comment]
Should add sharpening stones and weapon oils and such to this too

**Comment by Pewtro** [comment]
Weightstones are also a thing https://shadowlands.wowhead.com/spells/professions/blacksmithing/shadowlands-plans/weapons-mods
