### ISSUE TITLE
[Shadowlands] [Mage] Conduits checklist

### ISSUE THREAD

**Issue by Dambroda** [WoWAnalyzer/WoWAnalyzer#3675]
Other related issues:
-  #3657 Core Class Changes
- #3721 Legendaries

Conduits
-----
####  Shared Endurance
*these are not performance based and probably low priority, but still might be worth tracking the stats if we have time*
- [ ] [Cryro-Freeze](https://shadowlands.wowhead.com/spell=337123/cryo-freeze) (While inside Ice Block, you heal for X% of max HP over the duration)
- [x] [Diverted Energy](https://shadowlands.wowhead.com/spell=337136/diverted-energy) (Your Barriers heal you for X% of the damage absorbed)
- [x] [Tempest Barrier](https://shadowlands.wowhead.com/spell=337293/tempest-barrier) (Gain a shield that absorbs X% of your maximum HP for 15% after you Blink)

#### Shared Finesse
- [x] [Flow of Time](https://shadowlands.wowhead.com/spell=336636/flow-of-time) (The cooldown of Blink is reduced by X seconds) - *Needs either spellbook updated to change CD or a module to reduce it manually each cast*
- [ ] [Incantation of Swiftness](https://shadowlands.wowhead.com/spell=337275/incantation-of-swiftness) (Invisibility increases your movespeed by X% for 6 seconds) - *probably not worth tracking*
- [x] [Winter's Protection](https://shadowlands.wowhead.com/spell=336613/winters-protection) (The cooldown of Ice Block is reduced by X sec.) - *same as flow of time, needs CD updated*
- [x] [Grounding Surge](https://shadowlands.wowhead.com/spell=336777/grounding-surge) (Successfully interrupting an enemy with Counterspell reduces its cooldown by X sec) - ***need more info**, do we know if it was successful? probably not worth tracking as a statistic but at least getting the cooldown reduction right will help reduce CD module errors*

#### Arcane Throughput
- [x] [Arcane Prodigy](https://shadowlands.wowhead.com/spell=336873/arcane-prodigy) (Arcane Missiles reduces the cooldown of Arcane Power by X sec.) - *Definitely needs a module to reduce the CD. For statistics, I think it would be great to see the total CD reduction, the CD reduction wasted (by casting AM while AP is not on CD), and then maybe even seeing if the CD reduction gave you an extra cast or not*
- [x] [Artifice of the Archmage](https://shadowlands.wowhead.com/spell=337240/artifice-of-the-archmage) (Your Arcane Barrage has a X% chance to grant 2 Arcane Charges) - *Need to ensure the energize events are working properly to track charges, and might be worth seeing the number of free charges granted?*
- [ ] [Magi's Brand](https://shadowlands.wowhead.com/spell=337192/magis-brand) (Touch of the Magi accumulates an additional X% of the damage you deal.) - *No rotational change, but could be worth a statistic*
- [ ] [Nether Precision](https://shadowlands.wowhead.com/spell=336886/nether-precision) (Consuming Clearcasting increases the damage of your next 2 Arcane Blasts by X%) - *I'm going to assume this will change the rotation, ensuring that you don't chain AM missiles together and put in two AB's between them. Probably worth a checklist item if the person is using this conduit, plus a statistic for damage gained.*

#### Fire Throughput
- [ ] [Flame Accretion](https://shadowlands.wowhead.com/spell=337224/flame-accretion) (Fireball grants X% mastery when it fails to critically strike) - *probably just an average mastery gained stat? need TCs to find out if this is at all important to anything else*
- [x] [Master Flame](https://shadowlands.wowhead.com/spell=336852/master-flame) (Flamestrike damage and radius is increased by X%) - *this conduit will probably change the breakpoints for when you cast flamestrike. might be worth a checklist item if it does change the rotation, otherwise just a stat for estimated damage gained*
- [x] [Infernal Cascade](https://shadowlands.wowhead.com/spell=336821/infernal-cascade) (While Combustion is active, your Fire Blast grants you X% increased fire damage for 5 sec, stacking up to three times.) - *Need TCs to find out if it's worth optimizing this like blaster master, or just ignoring it and letting it be passive. Determines need for checklist item vs just a damage statistic*
- [x] [Controlled Destruction](https://shadowlands.wowhead.com/spell=341325/controlled-destruction) *Damage statistic*

#### Frost Throughput
- [x] [Shivering Core](https://shadowlands.wowhead.com/spell=336472/shivering-core) (Blizzard damage and snare increased by X%) - *Might change the blizzard breakpoints, especially with the blizzard talent. That + damage statistic*
- [x] [Unrelenting Cold](https://shadowlands.wowhead.com/spell=336460/unrelenting-cold) (Frozen orb damage is increased by X%) - *Just a damage statistic, probably*
- [x] [Icy Propulsion](https://shadowlands.wowhead.com/spell=336522/icy-propulsion) (While Icy Veins is active, your critical hits reduce its cooldown by X sec) - *Need cooldown reduction module and statistic for total reduction; maybe per IV cast?*
- [x] [Ice Bite](https://shadowlands.wowhead.com/spell=336569/ice-bite) (Increases the damage of Ice Lance against frozen enemies by X%) - *Just damage statistic module*

#### Covenant Throughput
- [x] [Ire of the Ascended](https://shadowlands.wowhead.com/spell=337058/ire-of-the-ascended) (Radiant Spark increases the damage your spells deal to the target by an additional X%) - *Just a damage statistic*
- [x] [Siphoned Malice](https://shadowlands.wowhead.com/spell=337087/siphoned-malice) (Each time a Mirrors of Torment is consumed your Spell Damage is increased by X% for 10 seconds, stacking 3 times.) - *Just a damage statistic, maybe info on the uptime*
- [ ] [Gift of the Lich](https://shadowlands.wowhead.com/spell=336999/gift-of-the-lich) (Deathborne's duration is increased by X sec.) - *Just a statistic on the increased uptime, maybe integrate into regular deathborne module to try and break down the damage increase there*
- [ ] [Discipline of the Grove](https://shadowlands.wowhead.com/spell=336992/discipline-of-the-grove) (Shifting Power channels X% faster.) - *who knows about this one, man*
