### ISSUE TITLE
Preservation Evoker support

### ISSUE THREAD

**Issue by trevorm4** [WoWAnalyzer/WoWAnalyzer#5387]
- [x] Echo and Resonating sphere modules - #5416
- [x] Time Lord module - #5469
- [x] Reversion Module - #5377 
- [x] Grace Period module - #5378
- [x] Field of Dreams module - #5423
- [x] Essence burst and Essence attunement modules - #5419
- [x] Bountiful bloom and Emerald Blossom modules - #5422
- [x] Cycle of Life Sources/Breakdown - #5471
- [x] Renewing Breath Contribution Module - #5468
- [x] Call of Ysera module - #5390 
- [x] Checklists for core ability usage (keep ve, sb, and reversion on cd) - #5472

**Comment by trevorm4** [comment]
Closing as we have implemented baseline stuff
