### ISSUE TITLE
Remove support for Shadowlands on Dragonflight branch

### ISSUE THREAD

**Issue by ToppleTheNun** [WoWAnalyzer/WoWAnalyzer#5450]
There are multiple Shadowlands specific things that can be removed.

- [x] Encounter Stats broken by new talent system (#5445)
- [x] Shadowlands specific item analyzers (#5448)
- [x] Deprecate Shadowlands specific combatant info (#5447)
- [x] Remove Shadowlands specific combatant info (#5461)
- [x] Remove raids from `src/game/ZONES` (#5449)
- [x] Remove raids from `src/game/raids` (#5460)
- [x] Clean out references to SL items and spells in `src/parser/retail/modules/items` (#5453, #5474)
- [x] Remove `src/common/ITEMS/shadowlands` (#5515)
- [ ] Remove `src/common/SPELLS/shadowlands`
