### ISSUE TITLE
Unholy Death Knight

### ISSUE THREAD

**Issue by jjs451** [WoWAnalyzer/WoWAnalyzer#601]
Use this issue to discuss features for this spec. Let us know when you're working on something, or plan to work on something.

Currently being maintained by @jjs451

Can be contacted at Khazak#3360 on Discord.

**Comment by jjs451** [comment]
## TODO
- [ ] Virulent Plague uptime
- [ ] Improved Dark Transformation cooldown feedback by accounting for Shadow Infusion
- [ ] Improved Dark Arbiter cooldown feedback by accounting for Convergence of Fate
- [ ] Add support for Cooldowns tab

**Comment by Tzodk** [comment]
Pooling up of rp before the DA window
SS casts with 1 (or two) less wounds during DT
# of wounds popped with Apocalypse (should be 6 each time)
