### ISSUE TITLE
Devastation Evoker TWW support

### ISSUE THREAD

**Issue by Krealle** [WoWAnalyzer/WoWAnalyzer#6935]
### Scalecommander
- [x] Implement [Mass Disintegrate](https://www.wowhead.com/beta/spell=436335/mass-disintegrate) #6941 
   - [x] Causality CDR
   - [ ] Disintegrate graph should account for variable amount of ticks
   - [ ] Scintillation procs / damage distribution
- [x] Stats for damage amp from [Might of the Black Dragonflight](https://www.wowhead.com/beta/spell=441705/might-of-the-black-dragonflight) #6942 
- [x] Stats for damage amp from [Melt Armor](https://www.wowhead.com/beta/spell=441176/melt-armor?spellModifier=356809) #6943 
- [x] Stats for damage amp from [Unrelenting Siege](https://www.wowhead.com/beta/spell=441246/unrelenting-siege?spellModifier=356809) #6953
- [x] Stats for amount of extension from [Extended Battle](https://www.wowhead.com/beta/spell=441212/extended-battle) #7001
- [x] Stats for EB gen from [Diverted Power](https://www.wowhead.com/beta/spell=441219/diverted-power) #6955
- [x] Stats for CDR gained from [Wingleader](https://www.wowhead.com/beta/spell=441206/wingleader?spellModifier=356809) #7002
- [x] Reset `Hover` CD with [Slipstream](https://www.wowhead.com/beta/spell=441257/slipstream) #7003
- [x] Make `MajorDefensives` account for [Hardened Scales](https://www.wowhead.com/beta/spell=441180/hardened-scales)  #7004
- [ ] ~~Maybe Implement [Maneuverability](https://www.wowhead.com/beta/spell=433871/maneuverability)?~~
- [ ] ~~Implement [Bombardments](https://www.wowhead.com/beta/spell=434300/bombardments?spellModifier=356809)~~

### Flameshaper

- [x] Make `MajorDefensives` account for [Lifecinders](https://www.wowhead.com/beta/spell=444322/lifecinders) #7004

### Talents

- [ ] Track procs from [Snapfire](https://www.wowhead.com/beta/spell=370783/snapfire)
   - [ ] Reset `Firestorm` cooldown on procs
- [ ] Implement [Imminent Destruction](https://www.wowhead.com/beta/spell=370781/imminent-destruction)
- [ ] [Charged Blast](https://www.wowhead.com/beta/spell=370455/charged-blast)

### Cleanup

- [x] Implement Always Be Casting module.
- [x] Update `Shattering Star` amped spell list.
- [x] Decide what to do with APL check.
- [x] Dragonrage section should be made into windows that can be cycled between.
- [x] Clean up legacy modules.
- [x] Double check talent values have been updated.
- [x] Make sure `Essence Graph` is still accurate.
