### ISSUE TITLE
[Holy Paladin] The War Within support

### ISSUE THREAD

**Issue by Texleretour** [WoWAnalyzer/WoWAnalyzer#6959]
This acts as a non-exhaustive to-do list for Holy Paladin support. I'm working on these items, but feel free to contribute or add any new things or discuss my items. We need to bring back Hpal its former glory :) Note that I'm a melee player so I will probably focus on this way of playing the spec.

The checklist/suggestions thing has been so left out that I think we're better off migrating to a true guide right away.

### Guide prototyping
- Core spells and buffs
  - [x] Holy Shock cast efficiency #6961 
  - [x] Holy Prism cast efficiency #6961 
  - [x] Beacon of virtue cast efficiency / Beacons of Light and Faith uptime #6961 
  - [ ] Beacon of virtue cast breakdown (healing done, overhealing, etc)
  - [ ] Beacons of  Light/Faith targets review
  - [ ] Spenders cast breakdown
  - [x] Holy power tracking (like Sheilun's Gift cloud efficiency - Mistweaver guide) #6961 
  - [ ] Judgement cast efficiency
 
- Healing cooldowns
  - [x] Avenging wrath, Divine Toll, Tyr's Deliverance, Hand of Divinity, Aura mastery, Blessing of sacrifice cast efficiencies #6961 
  - Avenging Crusader 
    - [ ] uptime/cast efficiency
    - [ ] Action priority list during cooldown 

- Other cooldowns and buffs
  - [ ] Empyrean Legacy
  - [ ] Divine Favor
  - [x] Blessings of Seasons #6961 

- Core rotation
  - [ ] Action priority list 

- [ ] Melee uptime and ABC (idk where to put that yet) + use of Tower of Radiance when out of melee range

### "New" talents
- [x] Overflowing light absorb stat #6973 
- [ ] Light's protection effective damage reduction stat
- [ ] Tower of radiance

### Hero talents
- Lightsmith
- Herald of the sun
  - [ ] Prepping Dawnlights before Avenging Wrath
  - [ ] Positioning during Sun's Avatar to maximize its healing
  - [ ] Dawnlight wasting
  - [ ] Update Holy Prism's Subsection explanation for Dawnlight and Aurora

### Cleanup
There's a lot to do here

### Other
- [ ] T32
- [ ] Reorganize Guide's "Core" Section to match priority list
