### ISSUE TITLE
[Arms/Fury Warrior] Wishlist/todo

### ISSUE THREAD

**Issue by oBusk** [WoWAnalyzer/WoWAnalyzer#7065]
Hey, since I've been working on various improvements for both Fury and Arms warriors, and I have plenty of ideas of what needs/should be implemented, I figured I'd write them down in an issue so that I/we can keep track of them. I made a shared ticket for fury/arms since I hope to work on both, and there's some overlap with Slayer being the preferred specialization for now.

I've already put in a lot of work to track rage generation/spending correctly. This will aid various guides/analysation happening at later stages in the pipeline. My view is still that the goal should be to get to a stage where all spells/cooldowns are tracked correctly, meaning SpellUsable is not complaining about spells being used before cooldown is over, GCD mismatches etc. From my view, rage is tracked as accurately as I think is plausible at this stage. Then there's plenty of statistics we can implement which provides some value in a theorycrafting sense, like damage effect of various talents, set bonuses etc. And then at some point, I'd love to have one of these fancy guide pages that a lot of specs have nowadays.

# Tracking

What tracking is needed to be implemented to improve accuracy of tracking of spells and cooldowns

### Shared

- [ ] (Arms+Fury) Handle [Unhinged](https://www.wowhead.com/spell=386628/unhinged?spellModifier=137049) so that SpellUsable is not confused that MS/BT/BB is cast during Bladestorm

### Slayer
- [ ] Bladestorm cooldown reduction from [Unrelenting Onslaught](https://www.wowhead.com/spell=444780/unrelenting-onslaught)
- [ ] Heroic Leap/Charge cooldown reduction from [Vicious Agility](https://www.wowhead.com/spell=444777/vicious-agility)

### Colossus 
- [ ] Track [Demolish](https://www.wowhead.com/spell=436358/demolish)
  - [ ] Cooldown reduction from [Dominance of the Colossus](https://www.wowhead.com/spell=429636/dominance-of-the-colossus)
- [ ] Shockwave cooldown by [Earthquaker](https://www.wowhead.com/spell=440992/earthquaker)
- [ ] (Arms) Bladestorm cooldown reduction from [Anger Management](https://www.wowhead.com/spell=152278/anger-management?spellModifier=137049)

### Mountain Thane
- [ ] Track [Thunder Blast](https://www.wowhead.com/spell=435607/thunder-blast)
- [ ] Cooldown reduction of Shield Slam/Bloodthirst from [Burst of Power](https://www.wowhead.com/spell=437118/burst-of-power?spellModifier=137050)
- [ ] Increased cooldown on Storm Bolt from [Storm bolts](https://www.wowhead.com/spell=436162/storm-bolts)
- [ ] Track Thunder Clap cooldown reset from [Avatar of the Storm](https://www.wowhead.com/spell=437134/avatar-of-the-storm)

# Statistics

### Shared 

- [ ] (Arms+Fury) Set bonuses - I'ts always fun to see how much damage the set bonuses deal! Should be very straight forward to track for both Fury and Arms
- [ ] Damage contribution from the increased bleed damage of [Thunderous Words](https://www.wowhead.com/spell=384969/thunderous-words). Would be interesting to see how much extra damage is gained by this talent, since it's not very obvious by just looking at Warcraftlogs. Especially interesting when used in combination with [Skullsplitter](https://www.wowhead.com/spell=260643/skullsplitter)

### Arms

- [ ] Damage of the bleed increase of [Skullsplitter](https://www.wowhead.com/spell=260643/skullsplitter). One of these things that is very hard to figure out by just looking at Warcraftlogs, so would be interesting to see.

# Guide

Classes now often have a "guide" page which shows various breakdowns acompanied with explanations of why certain things are important. They look really nice and should be looked into.

There should be some research in what the biggest impact mistake is for fury/arms warrior that should be the priority of the guide page to make provide the biggest help possible. 

Here's some of the specs that has nice guides that we can look at for inspiration. (Skipping casters, healers, augmentation and tanks since they have other priorities than DPS warrior)

- [Windwalker Monk](https://wowanalyzer.com/report/Z4zLYfWB8HJTjCNQ/6-Heroic+Ulgrax+the+Devourer+-+Kill+(5:53)/Pandanaconda/standard)
- [Havoc Demon Hunter](https://wowanalyzer.com/report/pKHj3mbcNT9wvY2n/43-Heroic+Ulgrax+the+Devourer+-+Kill+(5:57)/Lilith/standard)
- [Feral Druid](https://wowanalyzer.com/report/BA3qy8mdjrCc67a9/30-Heroic+Ulgrax+the+Devourer+-+Kill+(6:55)/Ithkahel/standard)
- [Assasination Rogue](https://wowanalyzer.com/report/HQ6MZ9xRGD4yckFq/26-Heroic+Ulgrax+the+Devourer+-+Kill+(7:02)/%C3%80k%C3%A0g%C3%A0m%C3%AE/standard)
- [Enhancement Shaman](https://wowanalyzer.com/report/rBw1MaKp8xcvF7TC/2-Heroic+Ulgrax+the+Devourer+-+Kill+(6:25)/Elektriker/standard)
